apiVersion: v1
kind: Secret
metadata:
  name: coordinator-secrets
  namespace: pairdb
  labels:
    app: coordinator
    component: coordinator
type: Opaque
stringData:
  database.user: "coordinator"
  database.password: "changeme"
  redis.password: ""

