apiVersion: v1
kind: Service
metadata:
  name: pairdb-storage-node-headless
  namespace: pairdb
  labels:
    app: pairdb-storage-node
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: grpc
  - port: 7946
    targetPort: 7946
    protocol: TCP
    name: gossip
  selector:
    app: pairdb-storage-node

